# Generated by Django 3.1.2 on 2021-01-26 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210126_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 26, 1, 25, 54, 666301, tzinfo=utc)),
        ),
    ]
